export const PortfolioData = [
  {
    id: 1,
    src: "/public/images/video-game-trivia.png",
    alt: "Video Game Trivia",
    title: "Video Game Trivia",
    // linkOne: "https://dev-rome.github.io/",
    linkOne: "https://github.com/dev-rome/dev-rome.github.io",
    linkTwo: "https://dev-rome.github.io/",
  },
  {
    id: 2,
    src: "/public/images/tenant-estate.png",
    alt: "Tenant Estate",
    title: "Tenant Estate",
    // linkOne: "https://enigmatic-anchorage-66839.herokuapp.com/buy",
    linkOne: "https://github.com/dev-rome/Tenant-Estate",
    linkTwo: "https://enigmatic-anchorage-66839.herokuapp.com/buy",
  },
  {
    id: 3,
    src: "/public/images/profolio.png",
    alt: "Pro-folio",
    title: "Pro-folio",
    // linkOne: "https://pro-folio-njt.netlify.app/",
    linkOne: "https://github.com/dev-rome/project3_frontend",
    linkTwo: "https://pro-folio-njt.netlify.app/",
  },
  {
    id: 4,
    src: "/public/images/gameoverflow.png",
    alt: "Gameoverflow",
    title: "Gameoverflow",
    // linkOne: "https://guarded-plateau-67104.herokuapp.com/",
    linkOne: "https://github.com/dev-rome/Gameoverflow",
    linkTwo: "https://guarded-plateau-67104.herokuapp.com/",
  },
  {
    id: 5,
    src: "/public/images/interactive-rating.png",
    alt: "Interactive Rating Component",
    title: "Interactive Rating Component",
    // linkOne: "https://mellow-arithmetic-b92b64.netlify.app/",
    linkOne: "https://github.com/dev-rome/Interactive-Rating-Component",
    linkTwo: "https://mellow-arithmetic-b92b64.netlify.app/",
  },
  {
    id: 6,
    src: "/public/images/product-preview-card.png",
    alt: "Product Preview Card Component",
    title: "Product Preview Card Component",
    // linkOne: "https://rainbow-unicorn-b60bf9.netlify.app/",
    linkOne: "https://github.com/dev-rome/Product-Preview-Card-Component",
    linkTwo: "https://rainbow-unicorn-b60bf9.netlify.app/",
  },
];
